### ISSUE TITLE
boot2docker depreciated

### ISSUE THREAD

**Issue by mmwtsn** [wercker/wercker-cli#30]
Most of the [wercker-cli documentation for usage on OS X](http://devcenter.wercker.com/learn/basics/the-wercker-cli.html) mentions boot2docker which [has officially been depreicated](https://docs.docker.com/installation/mac/) in favor of Docker Machine. A [Docker Toolbox](https://www.docker.com/toolbox) app has been released for OS X and Windows to manage the installation process.

Attempting to run boot2docker after the 1.8.x update will throw a depreciation error. Not sure how the affects the usage of Wercker's containers but it looks like Docker Machine's default IP is different than the one wercker-cli is expecting boot2docker to be running on.

**Comment by hatchan** [comment]
This repository is for the old wercker cli. Another ticket has already been opened in our support repository: wercker/support#119
