### ISSUE TITLE
WERCKER_OUTPUT_DIR behaves differently in cli

### ISSUE THREAD

**Issue by zeisss** [wercker/wercker-cli#33]
So I have a simple pipelines (https://github.com/zeisss/wercker-playground) that creates a .tar.gz in `$WERCKER_OUTPUT_DIR/dist/wercker-example.tar.gz` in the `build` pipeline. According to the docs, that folder is persisted, when its non empty (otherwise `WERCKER_SOURCE_DIR` would be persisted.

Sadly, when I run the deploy step, `WERCKER_OUTPUT_DIR` is empty again. Thanks to @flenter I learned that at least for wercker.com, persisting means making it available as `WERCKER_SOURCE_DIR` in the deploy pipeline. This is not the case for the `wercker-cli` though, which IMO is a bug.

**Comment by chrisdostert** [comment]
+1.
To recap: when you use the CLI writing to $WERCKER_OUTPUT_DIR is completely ignored

**Comment by zeisss** [comment]
actually I think this is the wrong repo and needs to be put into github.com/wercker/support

**Comment by NeMO84** [comment]
Might not be related but this issue provided the insight that WERCKER_SOURCE_DIR is the input location of WERCKER_OUTPUT_DIR from the build step. Is this documented anywhere?  (Sorry, not trying to hijack this issue)

**Comment by metral** [comment]
I've run into this as well using the CLI locally. `$WERCKER_SOURCE_DIR` in the deploy pipeline is empty, even though the build pipeline output files to `$WERCKER_OUTPUT_DIR`.

CLI version:
`wercker version 1.0.560 (Compiled at: 2016-07-14T18:47:38Z, Git commit: 45904587eedbad1503e0cf69fc151a551a888d88)`.

@termie PTAL 🙏

**Comment by faiq** [comment]
@metral can you please report this issue over to wercker/wercker

**Comment by faiq** [comment]
Once you do, I'm going to close out this repository for new issues

**Comment by metral** [comment]
@faiq here's the new issue https://github.com/wercker/wercker/issues/227

thanks!
